### ISSUE TITLE
Feature Request: DNS-over-QUIC (DoQ)

### ISSUE THREAD

**Issue by ghost** [pure-dns/puredns#2]

**Comment by fransallen** [comment]
DNS-over-QUIC support is now available at `quic://puredns.org:784`. Will be adding a setup guide to the website soon.

In the meantime, let me know if you have any questions/have problems with PureDNS.

**Comment by ghost** [comment]
> DNS-over-QUIC support is now available at `quic://puredns.org`. Will be adding a setup guide to the website soon.
> 
> In the meantime, let me know if you have any questions/have problems with PureDNS.

Are you certain it's up? This does not work for me.
![IMG_20220613_154316](https://user-images.githubusercontent.com/30196572/173315652-ffdf64e7-9f2e-4649-8410-90fc34427098.jpg)

**Comment by fransallen** [comment]
Correction. It's on port `784`. Try again?

**Comment by ghost** [comment]
> Correction. It's on port `784`. Try again?

[Based of section 8 of DoQ RFC](https://datatracker.ietf.org/doc/html/draft-ietf-dprive-dnsoquic-00#section-8) **port number 784 is for experimentations** and You should do it on port number 853 UDP instead.

**Comment by fransallen** [comment]
It will eventually be deployed on port 853 UDP, but since the protocol itself is currently being standardized, I'd like to keep it on port 784. To give a better picture of the experimentation.
